# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Socialtext-MailArchive
version:      0.01
version_from: lib/Socialtext/MailArchive.pm
installdirs:  site
requires:
    Socialtext::Resting:           0.15
    Socialtext::Resting::Utils:    0.08
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
