/*
   This JavaScript code was generated by Jemplate, the JavaScript
   Template Toolkit. Any changes made to this file will be lost the next
   time the templates are compiled.

   Copyright 2006 - Ingy döt Net - All rights reserved.
*/

if (typeof(Jemplate) == 'undefined')
    throw('Jemplate.js must be loaded before any Jemplate template files');

Jemplate.templateMap['container.tmpl'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
output += '<!-- head -->\n<div id="head">\n<h1><a rel="home" href="';
//line 3 "container.tmpl"
output += stash.get('site_base');
output += '">';
//line 3 "container.tmpl"
output += stash.get('site_title');
output += '</a></h1>\n<h2>';
//line 4 "container.tmpl"
output += stash.get('site_tagline');
output += '</h2>\n\n</div>\n\n<!-- left -->\n<div id="sidebar-1">\n';
//line 12 "container.tmpl"

// FOREACH 
(function() {
    var list = stash.get('sidebar_links');
    list = new Jemplate.Iterator(list);
    var retval = list.get_first();
    var value = retval[0];
    var done = retval[1];
    var oldloop;
    try { oldloop = stash.get('loop') } finally {}
    stash.set('loop', list);
    try {
        while (! done) {
            stash.data['l'] = value;
output += '\n    <p class="linklist"><a href="';
//line 11 "container.tmpl"
output += stash.get(['l', 0, 'href', 0]);
output += '" title="';
//line 11 "container.tmpl"
output += stash.get(['l', 0, 'title', 0]);
output += '">';
//line 11 "container.tmpl"
output += stash.get(['l', 0, 'name', 0]);
output += '</a><br />\n';;
            retval = list.get_next();
            value = retval[0];
            done = retval[1];
        }
    }
    catch(e) {
        throw(context.set_error(e, output));
    }
    stash.set('loop', oldloop);
})();

output += '\n';
//line 13 "container.tmpl"
output += stash.get('email');
output += '\n</div>\n\n<!-- right -->\n<div id="sidebar-2">\n  <img src="';
//line 18 "container.tmpl"
output += stash.get(['side_image', 0, 'src', 0]);
output += '" alt="';
//line 18 "container.tmpl"
output += stash.get(['side_image', 0, 'alt', 0]);
output += '"/><br />\n  <form action="';
//line 19 "container.tmpl"
output += stash.get(['rester', 0, 'server', 0]);
//line 19 "container.tmpl"
output += stash.get(['rester', 0, 'workspace', 0]);
output += '/index.cgi" method="get">\n    <p>Search<br />\n      <input type="text" name="search_term" value="" size="15" />\n      <input type="hidden" name="action" value="search" />\n    </p>\n  </form>\n\n  <p><a href="';
//line 26 "container.tmpl"
output += stash.get(['rester', 0, 'server', 0]);
output += '/noauth/feed/workspace';
//line 26 "container.tmpl"
output += stash.get(['rester', 0, 'workspace', 0]);
output += '?category=Recent%20Changes">RSS Feed</a></p>\n  ';
//line 27 "container.tmpl"
output += stash.get('sidebar_extra');
output += '\n</div>\n\n<!-- center -->\n<div id="content">\n</div>\n\n<!-- footer -->\n<div id="foot">All posts come from <a href="';
//line 35 "container.tmpl"
output += stash.get(['rester', 0, 'server', 0]);
//line 35 "container.tmpl"
output += stash.get(['rester', 0, 'workspace', 0]);
output += '/index.cgi?action=category_display;category=';
//line 35 "container.tmpl"
output += stash.get('post_tag');
output += ';tag=/';
//line 35 "container.tmpl"
output += stash.get('post_tag');
output += '">this wiki</a></div>\n\n\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

Jemplate.templateMap['head.tmpl'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
output += '<h1><a rel="home" href="';
//line 1 "head.tmpl"
output += stash.get('site_base');
output += '">';
//line 1 "head.tmpl"
output += stash.get('site_title');
output += '</a></h1>\n<h2>';
//line 2 "head.tmpl"
output += stash.get('site_tagline');
output += '</h2>\n\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

Jemplate.templateMap['posts.tmpl'] = function(context) {
    if (! context) throw('Jemplate function called without context\n');
    var stash = context.stash;
    var output = '';

    try {
//line 6 "posts.tmpl"

// FOREACH 
(function() {
    var list = stash.get('posts');
    list = new Jemplate.Iterator(list);
    var retval = list.get_first();
    var value = retval[0];
    var done = retval[1];
    var oldloop;
    try { oldloop = stash.get('loop') } finally {}
    stash.set('loop', list);
    try {
        while (! done) {
            stash.data['post'] = value;
output += '\n    <h3><a rel="bookmark" href="';
//line 2 "posts.tmpl"
output += stash.get(['post', 0, 'permalink', 0]);
output += '">';
//line 2 "posts.tmpl"
output += stash.get(['post', 0, 'title', 0]);
output += '</a> - ';
//line 2 "posts.tmpl"
output += stash.get(['post', 0, 'date', 0]);
output += '</h3>\n    ';
//line 3 "posts.tmpl"
output += stash.get(['post', 0, 'content', 0]);
output += '\n    <p class="comments_invite"><a href="';
//line 4 "posts.tmpl"
output += stash.get(['post', 0, 'permalink', 0]);
output += '">Comment here</a> | <a href="';
//line 4 "posts.tmpl"
output += stash.get(['post', 0, 'permalink', 0]);
output += '">Edit this post here</a></p>\n    <div align="center"><img src="http://awesnob.com/images/1.gif" style="height:1px;width:400px" class="divider" alt="" /></div>\n';;
            retval = list.get_next();
            value = retval[0];
            done = retval[1];
        }
    }
    catch(e) {
        throw(context.set_error(e, output));
    }
    stash.set('loop', oldloop);
})();

output += '\n';
    }
    catch(e) {
        var error = context.set_error(e, output);
        throw(error);
    }

    return output;
}

