#!/usr/bin/env perl
use strict;
use warnings;
use Socialtext::Resting::Getopt qw/get_rester/;
use Socialtext::WikiObject::TestPlan;
use Getopt::Long;
use Test::More qw/no_plan/;

# Script to run wiki tests outside of `make test` harness.

my $plan_page   = shift || die 'must supply a plan page';
my $test_server = shift || die 'must supply a test server';

my $rester = get_rester();

my $test_plan = Socialtext::WikiObject::TestPlan->new(
    rester => $rester,
    page => $plan_page,
    default_fixture => 'Null',
    fixture_args => {
        host => $ENV{selenium_host} || 'localhost',
        port => 4444,
        browser_url => $test_server,
        print_cmds => 1,
    },
);
$test_plan->run_tests;
exit;
